/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a34676f3-a0fa-41ef-a2c1-c3ff74027cc8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_38X45Lu2u",
    "aws_user_pools_web_client_id": "mtbfg4ea0e3alefpm76hmpeh5",
    "oauth": {}
};


export default awsmobile;
