#!/bin/bash
CONFIG_DIR=database/configuration

# create dist package, in which will be the entrypoint for /database/configuration access
rm -rf ${CONFIG_DIR}/dist
mkdir -p ${CONFIG_DIR}/dist

# copy environment files, so dontenv can access then
echo "copying env files to ${CONFIG_DIR}/dist/"
cp ${CONFIG_DIR}/.env.* ${CONFIG_DIR}/dist/

# build modules
echo "building typescript modules..."
tsc -d ${CONFIG_DIR}/index.ts --outDir ${CONFIG_DIR}/dist

# configure package.json to point to the dist folder
echo "configuring ${CONFIG_DIR}/package.json to point to ${CONFIG_DIR}/dist"
touch ${CONFIG_DIR}/package.json
echo '{ "main": "dist/index.js", "description": "this file was auto-generated by build-database-config.sh script. Do not edit it" }' > ${CONFIG_DIR}/package.json

echo "done"
