#!/bin/bash
AWS_DIR=aws
CONFIG_DIR=${AWS_DIR}

# create dist package, in which will be the entrypoint
rm -rf ${CONFIG_DIR}/dist
mkdir -p ${CONFIG_DIR}/dist

# change from .js to .ts so tsc can works better
echo "copying ${AWS_DIR}/aws-exports.js to ${CONFIG_DIR}/dist/index.ts"
cp ${AWS_DIR}/aws-exports.js ${CONFIG_DIR}/dist/index.ts

# build modules
echo "building typescript modules..."
tsc -d ${CONFIG_DIR}/dist/index.ts

# configure package.json to point to the dist folder
echo "configuring ${CONFIG_DIR}/package.json to point to ${CONFIG_DIR}/dist"
touch ${CONFIG_DIR}/package.json
echo '{ "main": "dist/index.js", "description": "this file was auto-generated by a building script. Do not edit it, will be overwriten." }' > ${CONFIG_DIR}/package.json

echo "done"
