#!/bin/bash
CONFIG_DIR=aws
DIST_DIR=${CONFIG_DIR}/dist

# create dist package, in which will be the entrypoint
rm -rf ${DIST_DIR}
mkdir -p ${DIST_DIR}

# change from .js to .ts so tsc can works better
echo "copying ${CONFIG_DIR}/aws-exports.js to ${DIST_DIR}/index.ts"
cp ${CONFIG_DIR}/aws-exports.js ${DIST_DIR}/index.ts

# build modules
echo "building typescript modules..."
npx tsc -d ${DIST_DIR}/index.ts

# configure package.json to point to the dist folder
echo "configuring ${CONFIG_DIR}/package.json to point to ${DIST_DIR}"
touch ${CONFIG_DIR}/package.json
echo '{ "main": "dist/index.js", "description": "this file was auto-generated by a building script. Do not edit it, will be overwriten." }' > ${CONFIG_DIR}/package.json

echo "done"
