#!/bin/bash
CONFIG_DIR=source
DIST_DIR=dist

# create dist package, in which will be the entrypoint for /database/configuration access
rm -rf ${DIST_DIR}
mkdir -p ${DIST_DIR}

# # copy environment files, so dontenv can access then
# echo "copying env files to ${DIST_DIR}/"
# cp ${CONFIG_DIR}/.env.* ${DIST_DIR}

# build modules
echo "building typescript modules..."
npx tsc -d ${CONFIG_DIR}/index.ts --outDir ${DIST_DIR}

# configure package.json to point to the dist folder
# echo "configuring ${CONFIG_DIR}/package.json to point to ${DIST_DIR}"
# touch ${CONFIG_DIR}/package.json
# echo '{ "main": "dist/index.js", "description": "this file was auto-generated by build-database-config.sh script. Do not edit it" }' > ${CONFIG_DIR}/package.json

echo "done"
